### ISSUE TITLE
Needs a license

### ISSUE THREAD

**Issue by rafibaum** [InventivetalentDev/BossBarAPI#11]
I'm very appreciative of all the work you've done to create what appears to be a very robust BossBar API. However, you appear to have forgotten to include a license with the library, making it difficult to use legally. Can I suggest you add a license the program with the MIT license or some other permissive license so users can incorporate this code for whatever they wish? Thanks in advance.

**Comment by rafibaum** [comment]
I just saw there's a quasi-MIT license in the pom.xml. It'd be helpful if the license was more visible in a `LICENSE` file or something.

**Comment by InventivetalentDev** [comment]
Done! :)
